version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
    ignore:
      - dependency-name: 'vite'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@eslint/js'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'eslint'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - ci
